### ISSUE TITLE
Actual Plugin Version don't work with actual RRF Version 3.5.0-rc.3

### ISSUE THREAD

**Issue by CrazyCreator13** [Duet3D/EndstopsMonitorPlugin#2]
Actual Plugin Version don't work with actual RRF Version 3.5.0-rc.3

**Comment by dc42** [comment]
> Actual Plugin Version don't work with actual RRF Version 3.5.0-rc.3

I've no idea what you mean by this. Please provide more detail.

**Comment by CrazyCreator13** [comment]
My english is maybe to bad ;) 

The current version of the EndstopsMonitorPlugin (Version 3.5.0-b1) cannot be installed on RRF 3.5.0-rc3

**Comment by dc42** [comment]
Thanks, I've raised this with the developers.

**Comment by chrishamm** [comment]
Version 3.5.0 is now available, closing.
